spring:
  datasource:
    url: jdbc:h2:mem:bookstore
    user: sa
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true