DROP TABLE IF EXISTS autors;
CREATE TABLE autors(ID BIGINT PRIMARY KEY  auto_increment, NAME VARCHAR(255));
DROP TABLE IF EXISTS genres;
CREATE TABLE genres(ID BIGINT PRIMARY KEY  auto_increment, NAME VARCHAR(255));
DROP TABLE IF EXISTS books;
CREATE TABLE books(ID BIGINT PRIMARY KEY  auto_increment, NAME VARCHAR(255), AUTORID BIGINT , GENREID BIGINT );


